### ISSUE TITLE
pp numbers for some reason being inside logo of hitbloq, bl, and ss

### ISSUE THREAD

**Issue by mattydawhat** [no-1-noob/PPPredictor#21]
![image](https://github.com/no-1-noob/PPPredictor/assets/78245951/8c8a4ebf-121a-4848-94d3-adc56c963cf1)
1.36.2 using latest version

**Comment by no-1-noob** [comment]
@mattydawhat Have you found a workaround since the issue was closed?

**Comment by mattydawhat** [comment]
i actually dmed you on discord because i thought it was better for communication
