### ISSUE TITLE
Mod doesn't work on 1.29.1

### ISSUE THREAD

**Issue by AdiQVR** [no-1-noob/PPPredictor#27]
I made sure that the needed mod versions for 1.29 were installed but when i started the game i couldn't find the mod anywhere.

**Comment by no-1-noob** [comment]
Hi there,

two questions beforehand, is it both invisible in the main menu (after clicking on singleplayer) and (if you use it) in the counters+ overlay while playing?

Could be a compatibility issue with another mod.

Can you start a new game session, then navigate to the normal singleplayer menu, then close the game normally?
Afterwards please attach the log file of that session to this issue? (usually found somewhere like C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Logs)
And if it was created, the PPPredictor save file (found in C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\UserData\PPPredictorProfileInfo.json).

**Comment by AdiQVR** [comment]
Hello,

Well i tried to fing that file but it is not there.

**Comment by no-1-noob** [comment]
The logfile should always exist every mod logs into that. Try to find it like this:
In your Steam library right click beatsaber -> properties -> installed files -> click on "browse..."
Then your file explorer should open in the Beatsaber folder, enter the Logs folder there should be the "_latest.log" file from your last session.
You could also add the --verbose startoption to the game then you get a console window when the game starts where you can see the logs in realtime while you play. 
![image](https://github.com/user-attachments/assets/26e789d6-74d9-4bef-8667-991e2d1adc1d)

**Comment by AdiQVR** [comment]
Ok found it, here you go
[_latest.log](https://github.com/user-attachments/files/16849237/_latest.log)
and here is the other one
[PPPredictorProfileInfo.json](https://github.com/user-attachments/files/16849258/PPPredictorProfileInfo.json)

**Comment by no-1-noob** [comment]
It seems you are missing websocket-sharp 1.0.4
![image](https://github.com/user-attachments/assets/c28489a1-87b6-49e9-a46a-0349683cd8e4)

Just get the version for 1.29.0 (they are basically all the same)
https://beatmods.com/#/mods

**Comment by AdiQVR** [comment]
Thank you, it works now!
